insert into banderas values
(1,curdate(),curdate(),'Alemania','Alemania.png'),
(2,curdate(),curdate(),'Argentina','Argentina.jpg'),
(3,curdate(),curdate(),'Austria','Austria.png'),
(4 curdate(),curdate(),'Belgica','Belgica.png'),
(5,curdate(),curdate(),'Brasil','Brasil.png'),
(6,curdate(),curdate(),'Camerun','Camerun.png'),
(7,curdate(),curdate(),'Costa De Marfil','CMarfil.png'),
(8,curdate(),curdate(),'Colombia','Colombia.png'),
(9,curdate(),curdate(),'Dinamarca','Dinamarca.png'),
(10,curdate(),curdate(),'Eslovenia','Eslovenia.png'),
(11,curdate(),curdate(),'España','Espania.png'),
(12,curdate(),curdate(),'Estados Unidos','Estados_Unidos.png'),
(13,curdate(),curdate(),'Francia','Francia.png'),
(14,curdate(),curdate(),'Gales','Gales.png'),
(15,curdate(),curdate(),'Ghana','Ghana.png'),
(16,curdate(),curdate(),'Inglaterra','Inglaterra.png')