insert into banderas values
(1, curdate(). 'Alemania', 'Alemania.png'),
(2, curdate(), 'Arggntina', 'Arggntina.png'),
(3, curdate(), 'Austria', 'Austria.png'),
(4, curdate(), 'Belgica', 'Belgica.png').
(5, curdate(), 'Camerún', 'Camerun.png'),
(6, curdate(), 'Chile', 'Chile.png'),
(7, curdate(), 'Costa de Marfll', 'CMarfil.png'),
(8, curdate(), 'Colombia', 'Colombia.png'),
(9, curdate(), 'Croacia', 'Croacia.png'),
(10, curdate(), 'Dinamarca', 'Dinamarca.png'),
(11, curdate(), 'Eslovenia', 'Eslovenia.png'),
(12, curdate(), 'España', 'Espania.png'),
(13, curdate(), 'Estados Unidos', 'Estados_Unidos,png'),
(14, curdate(), 'Francia', 'Francia.png'),
(15, curdate(), 'Gales', 'Gales.png'),
(16, curdate(), 'Ghana', 'Ghana.png'),
(17, curdate(), 'Inglaterra', 'Inglaterra.png'),
(18, curdate(), 'Marruecos', 'Marruecos,png'),
(19, curdate(), 'Mexico', 'Mexico.png'),
(20, curdate(), 'Noruega', 'Noruega.png'),
(21, curdate(), 'Paises Bajos', 'Paises_Bajos.png'),
(22, curdate(), 'Polonia', 'Polonia.png'),
(23, curdate(), 'Portugal', 'Portugal.png'),
(24, curdate(), 'Senegal', 'Senegal.png'),
(25, curdate(), 'Serbia', 'Serbia.png'),
(26, curdate(), 'Suecia', 'Suecia.png'),
(27, curdate(), 'Turquia', 'Turquia.png'),
(28, curdate(), 'Ucrania', 'Ucrania.png'),
(29, curdate(), 'Uruguay', 'Uruguay.png');



insert into equipos values
(1, curdate(), 'Milan', 'AC_Milan.png'),
(2, curdate(), 'Ajax', 'AFC_Ajax.png'),
(3, curdate(), 'Arsenal', 'Arsenal.png'),
(4, curdate(), 'Atletico de Madrid', 'Atletico.png'),
(5, curdate(), 'Borussia Dortmund', 'Borussia_Dortmund.png'),
(6, curdate(), 'Chelsea', 'Chelsea.png'),
(7, curdate(), 'Barcelona', 'FC_Barcelona.png'),
(8, curdate(), 'Bayer Munich', 'FC_Bayern_Munchen.png'),
(9, curdate(). 'Oporto', 'FC_Porto.png'),
(10, curdate(), 'Inter', 'Inter_Milan.png'),
(11, curdate(), 'Juventus', 'Juventus.png'),
(12, curdate(), 'Liverpool', 'Liveerpool.png'),
(13, curdate(), 'Manchester City', 'Manchester_City.png'),
(14, curdate(), 'Manchester United', 'Manchester_United.png'),
(15, curdate(), 'PSG', 'PSG.png'),
(16, curdate(), 'Real Madrid', 'Real_Madrid.png'),
(17, curdate(), 'Benfica', 'SL_Benfica'),
(18, curdate(), 'Sporting', 'Sporting_Lisboa'),
(18, curdate(), 'Tottenham', 'Tottenham.png');





insert into juggadors values
(1, curdate(), 'DC', 'Younes', 'Amin' 'Amin_Younes_AJA.jpg', 1),
(2, curdate(),  'DFC', 'Martinez', 'Lisandro', 'licha_AJA.jpg', 2),
(3, curdate(), 'DC', 'Bodul', 'Darko', 'Darko_Bodul.jpg', 3),
(4, curdate(), 'DFC', 'Vertonghen', 'Jan', 'Jan_Vertonghen_AJA.jpg', 4),
(5, curdate===(), 'ED', 'Antony', 'Antony0', 'antony_AJA-jpg', 5),
(6, curdate(), 'POR', 'Onana'. 'André' , 'Onana_AJA.jpg', 6),
(7, curdate(), 'DFC', 'Sanchez', 'Davinson', 'davinson-sanchez.jpg', 7).
(8, curdate(), 'DC', 'Haller', 'Sebastien', 'Sebastien_Haller_AJA.jpg', 8),
(9, curdate(), 'LI', 'Sosa', 'Borna', 'Borna_Sosa_AJA.jpg', 9),
(10, curdate(), 'MC', 'Eriksen', 'Christian', 'eriksen_AJA.jpg', 10),
(11, curdate(), 'DC', 'Krkic', 'Bojan', 'Bojan_Krkic_AJA.jpg', 11),
(12, curdate(), 'LD', 'Dest', 'Sergiño', 'dest_AJA', 12),
(13, curdate(), 'DC', 'Sanogo',  'Yaya', 'Yaya_Sanogo.jpg', 13),
(14, curdate(), 'MCD', 'Quansah'. 'Kwame', 'Kwame_Quansah_AJA.jpg', 15),
(15, curdate(), 'MCD', 'Henderson', 'Jordan', 'Jordan_Henderson_AJA.jpg', 16),
(16, curdate(), 'DFC'. 'Rugani', 'Daniele','Daniele_Rugani_AJA.jpg', 18),
(17, curdate(), 'ED', 'Ziyech', 'Hakim', 'Ziyech_AJA.jpg', 19),
(18, curdate(), 'MCD', 'Alvarez', 'Edson', 'edson_alvarez_AJA.jpg', 20),
(19, curdate(), 'LD'. 'Bergdolmo', 'André', 'Andre', 'Andre_Bergdolmo_AJA.jpg', 21),
(20, curdate(), 'DFC', 'Blind', 'Daley', 'DB_AJA.jpg', 22),
(21, curdate(), 'DC', 'Milik', 'Arkadius', 'Arkadiusz_Milik_AJA..jpg', 23),
(22, curdate(), 'POR', 'Varela', 'Bruno', 'Bruno_Varela_AJA.jpg', 24),
(23, curdate(), 'MC', 'Coulibaly', 'Mamadou', 'Mamadou_Coulibaly_AJA.jpg', 25),
(24, curdate(), 'DC', 'Zigic', 'Nikola', 'Nikola_Zigic_AJA.jpg', 26),
(25, curdate(), 'DC', 'Ibrahimovic', 'Zlatan', 'ibra_AJA.jpg', 27),
(26, curdate(), 'DC', 'Gomzalez', 'Lorenzo', 'Lorenzo_Gonzalez_AJA.jpg', 28),
(27, curdate(), 'MCO', 'Sahin', 'Nuri', 'Nuri_Sahin_AJA.jpg', 29),
(28, curdate(), 'DC', 'Suarez', 'Luis', 'luis_suarez_AJA.jpg', 31).



(29, curdate(), 'EI', 'Musiala', 'Jamal', 'Musiala_BAY.jpg', 1),
(30. curdate(), 'DFC', 'Demilchelis', 'Martin', 'Demichelis_BAY.jpg', 2),
(31, curdate(), 'DFC', 'Alaba', 'David', 'Alaba_BAY.jpg', 3),
(32, curdate(), 'DFC', ' van Buyten', 'Daniel', 'Van_Buyten_BAY-jpg', 4),
(33. curdate(), 'EI', 'Coutihho', 'Phillippe', 'Coutinho_BAY.jpg', 5),
(34, curdate(), 'DC', 'Moting', 'ChouPO' 'Choupo_Motinmg_BAY.jpg', 6),
(35, curdate(), 'MCD', 'Vidal', 'Arturo', 'Arturo_Vidal_BAY.jpg', 7),
(36, curdate(), 'MCO', 'Rodriguez', 'James', 'James_Rodriguez_BAT.jpg', 8),
(37, curdate(). 'MCD', 'Hojberg', 'Pierre-Emile', 'Hojbergv.jpg', 10),
(38, curdate(), 'LD', 'Odriozola', 'Álvaro', 'Odriozola_BAY', 12),
(39, curdate(), 'MCO', 'Donovan', 'Landon', 'Landon_Donovan_BAY.jpg', 13),
(40, curdate(), 'LD', 'Boey', 'Nathan', 'Boey_BAY.jpg', 14),
(41, curdate(), 'DC', 'Kane', 'Harry', 'Kane_BAY', 17),
(42, curdate(), 'DC', 'Toni', 'Luca', 'Luca_Toni_BAY.jpg', 18),
(43, curdate(), 'DFC', 'Benatia', 'Medhi', 'Benatia_BAY.jpg', 19),
(44, curdate(), 'MC', 'Gravenberch', 'Ryan', 'Gravenberch_BAY', 22),
(45, curdate(), 'DC', 'Lewandowski', 'Robert', 'Lewandowski_BAY.jpg', 23),
(46, curdate(), 'MCD', 'Palhinha', 'Joao', 'Palhinha_BAY.jpg', 24),
(47, curdate(), 'EI', 'Mané', 'Sadio', 'Mane_BAY.jpg', 25),
(48, curdate(), 'DFC', 'Andersson', 'Patrik_Andersaon_BAY.jpg', 26),
(49, curdate(), 'ED', 'Shaqiri', 'Xherdan', 'Shaqiri_BAY.jpg', 27),
(50, curdate(), 'DC', 'Altintop', 'Hamit', 'Altintop_BAY.jpg', 28),
(51, curdate(), 'DC', 'Shevchenko', 'Andriy', 'Anatolly_Tymoschuk_BAY.jpg', 30),



(52, curdate(), 'MCO', 'Reus', 'Marco', 'Reus_BVB.jpg', 1),
(53, curdate(), 'DFC', 'Balerdi', 'Leonardo', 'Balerdi_BVB.jpg', 2),
(54, curdate(), 'MC', 'Sabitzer', 'Marcel', 'Sabitzer_BVB.jpg', 3),
(55, curdate(), 'EI', 'Hazard', 'Thorgan_Hazard_BVB.jpg', 4),
(56, curdate(), 'CAR', 'Couto', 'Yan', 'Yan_Couto_BVB.jpg', 5),
(57, curdate(), 'MCO', 'Barrios', 'Adrian', 'Adrian_Barrios_BVB.jpg', 8),
(58,. curdate(), 'DC', 'Haller', 'Sebastien', 'Haller_BVB.jpg', 9),
(60, curdate(), 'MCD', 'Delaney', 'Thomas', .'Delaney_BVB.ljpg', 10),
(61, curdate(), 'MC', 'Kampl', 'Toni', ¡'Kampl_BVB.jpg¡', 11),
(62, curdate(), 'DC', 'Alcacer', 'Paco', 'Paco_Alcacer_BVB.jpg', 12),
(63, curdate(). 'EI', 'Reyna', 'Giovanni', 'Reyna_BVB.jpg', 13),
(64, curdate(), 'DFC', 'Coulibaly', 'Soumaila', 'Coulibaly_BVB.jpg', 14),
(65, curdate(), 'DC', 'Boateng', 'Kevin-Prince', 'Boateng_BVB.jpg', 16),
